//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETMFDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_HCPInfo
    {
        public int Id { get; set; }
        public int ProjectId { get; set; }
        public string HospitalHCPName { get; set; }
        public string HospitalReceipt { get; set; }
        public string EmployeeName { get; set; }
        public Nullable<int> EmployeeProduct { get; set; }
        public Nullable<int> EmployeeDA { get; set; }
        public string EmployeePhoneNumber { get; set; }
        public Nullable<int> EmployeeMarketArea { get; set; }
        public string EmployeeEMail { get; set; }
        public string HCPCRMCode { get; set; }
        public string HCPFirstName { get; set; }
        public string HCPSecondName { get; set; }
        public Nullable<int> HCPSex { get; set; }
        public string HCPPhoneNumber { get; set; }
        public string HCPBirthday { get; set; }
        public Nullable<int> HCPPassportType { get; set; }
        public string HCPPassportNumber { get; set; }
        public string HCPPassportSignAddress { get; set; }
        public string HCPPassportStartDate { get; set; }
        public string HCPPassportEndDate { get; set; }
        public string HCPCity { get; set; }
        public string HCPDegree { get; set; }
        public string HCPLayer { get; set; }
        public Nullable<int> HCPTitle { get; set; }
        public string HCPKeShi { get; set; }
        public string HCPUnit { get; set; }
        public string HCPMailAddress { get; set; }
        public string HCPMailCode { get; set; }
        public string HCPEMail { get; set; }
        public Nullable<int> HCPIsSpeaker { get; set; }
        public Nullable<int> RoomType { get; set; }
        public string RoomPartner { get; set; }
        public string OtherComments { get; set; }
        public Nullable<bool> OtherCancelAttend { get; set; }
        public string OtherCancelReason { get; set; }
        public Nullable<bool> PMAttended { get; set; }
        public Nullable<decimal> PMTotalCost { get; set; }
        public Nullable<bool> PMReceiptApprove { get; set; }
        public string HCPIsGetScore { get; set; }
        public string HospitalSpecialFile { get; set; }
        public string HCPDegree2 { get; set; }
        public string EmployeeEmergencyPerson { get; set; }
        public string EmployeeEmergencyPhone { get; set; }
        public Nullable<int> HCPIDType { get; set; }
        public string HCPIDNumber { get; set; }
        public Nullable<int> HCPBelongBudget { get; set; }
        public Nullable<decimal> HCPTrafficCost { get; set; }
        public Nullable<decimal> HCPLiveCost { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public Nullable<bool> Active { get; set; }
        public string MarketArea { get; set; }
        public string HCPLevel { get; set; }
        public Nullable<bool> IsAttend { get; set; }
        public Nullable<bool> IsLocal { get; set; }
        public string AttendType { get; set; }
        public Nullable<bool> IsMacth { get; set; }
        public string HCPProvince { get; set; }
        public string HospitalCode { get; set; }
    }
}
